name = "SMoReExamples"
uuid = "6350f8a7-223e-46b9-a8d9-8cdf5ad5c457"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
